image: ghcr.io/tjpalanca/tjcloud/gitpod

tasks:
  - name: Setup Julia Environment 
    init: |
      julia -e ';
        using Pkg
        Pkg.activate("/workspace/AdventOfCode.jl")
        Pkg.instantiate(; verbose = true);
      '

vscode:
  extensions:
    - julialang.language-julia
