image: ghcr.io/tjpalanca/tjcloud/gitpod:latest

tasks:
  - name: Setup Julia Environment 
    init: pwd && julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate();'

vscode:
  extensions:
    - julialang.language-julia
