image: ghcr.io/tjpalanca/tjcloud/gitpod

tasks:
  - name: Setup Julia Environment 
    init: |
      julia -e '
        import Pkg
        Pkg.activate(".")
        Pkg.instantiate(; verbose = true)
      '

vscode:
  extensions:
    - julialang.language-julia
