image: ghcr.io/tjpalanca/tjcloud/gitpod:latest

tasks:
  - name: Setup Julia Environment 
    init: julia --project --color=yes -e "import Pkg; println(Pkg.project())"

vscode:
  extensions:
    - julialang.language-julia
